### ISSUE TITLE
Git pre-commit hook discards in-progress merge state

### ISSUE THREAD

**Issue by damienprystay** [houseabsolute/perl-code-tidyall#100]
It seems that `Code::TidyAll::Git::Precommit->check` will break an in-progress merge (e.g. when the merge had conflicts that needed to be manually resolved).

Steps to reproduce:
1. Get into the in-progress merge state by doing a merge that produces conflicts, or with `git merge --no-ff --no-commit <branch>`.
2. `git status` shows `All conflicts fixed but you are still merging. (use "git commit" to conclude merge)`
3. `git commit -m "Merge branch foo"`: the pre-commit hooks run, then the commit fails with `fatal: could not open '.git/MERGE_HEAD' for reading: No such file or directory`
4. `git status` no longer indicates that a merge is in progress, though the file changes are still staged.

My guess is that the `git stash save` the hook starts with is to blame, as the same behaviour can be produced simply by manually doing a `git stash save` while in the in-progress merge state. [This SO comment](https://stackoverflow.com/questions/34685407/can-i-git-stash-a-merge-in-progress#comment57127118_34685407) suggests that `git stash` intrinsically breaks an in-progress merge due to discarding git metadata about the merge, but I haven't been able to find anything to corroborate (other than first-hand observation).

Git version is 2.23.0 (macOS), TidyAll version 0.75.

**Comment by autarch** [comment]
Yes, definitely a bug. A PR would be welcome, of course, or you could try convince my boss to let me fix it on company time ;)

**Comment by autarch** [comment]
Fixed in 0.78

**Comment by damienprystay** [comment]
Thank you!
