### ISSUE TITLE
Plugin loading fails with Code::TidyAll 0.41

### ISSUE THREAD

**Issue by mgruner** [houseabsolute/perl-code-tidyall#53]
Hello.

Since v. 0.41 we have failing unit tests for some custom TidyAll plugins. Our unit test loads them with 
```
my $Plugin = $PluginModule->new(
                    class   => $PluginModule,
                    name    => $PluginModule,
                    tidyall => $TidyAll,

                    #%$plugin_conf
                );
```

which worked fine until 0.40, and now fails in 0.41. I can confirm this for Ubuntu 12.04 and Mac OS. There is an unclear message:

```
 Message: Attempt to reload TidyAll/Plugin/OTRS/Base.pm aborted.
Compilation failed in require at (eval 432) line 2.
	...propagated at /System/Library/Perl/5.18/base.pm line 84.
BEGIN failed--compilation aborted at /ws/otrs5/Kernel//TidyAll/Plugin/OTRS/PO/Lint.pm line 18.
```

Our plugins use a common base class via ```use base qw(TidyAll::Plugin::OTRS::Base);``` and this class also just does a ```use base qw(Code::TidyAll::Plugin);```. There the compiler seems to choke, even though I don't see any big changes from 0.40 to 0.41 in the code.

All code is available at https://github.com/OTRS/otrscodepolicy/tree/master/Kernel/TidyAll/Plugin/OTRS. A failing test run can be seen at https://travis-ci.org/OTRS/otrs/jobs/113671840.

I would be grateful for any hints about this problem. Do we need to adapt something in our source code?

Thanks and best regards, 
Martin

**Comment by autarch** [comment]
If you look at the full output you'll see that it's complaining about the version of Text::Diff that's installed. The latest version of Code::TidyAll requires Text::Diff 1.44+.

Cheers,

-dave

**Comment by mgruner** [comment]
Hello @autarch. Thanks for your reply, but it is not that simple. In this travis build, we install Code::TidyAll via cpanm, and this pulls Text::Diff in the latest version, you can see this in the collapsed cpanm log lines. Not sure at all why it complains about the Text::Diff version. I have the same locally; when updating Code::TidyAll via cpanm, Text::Diff is also updated, and still the different errors show up in our unit tests. Could you reopen this please? Can I provide any more information for you?

**Comment by mgruner** [comment]
Please see #54 for a fix for this issue.
