### ISSUE TITLE
0.44 breaks configuration parsing

### ISSUE THREAD

**Issue by mgruner** [houseabsolute/perl-code-tidyall#59]
Hello,
this example from the documentation works no longer:

```[PerlCritic]
select = lib/**/*.pm
ignore = lib/UtterHack.pm lib/OneTime/*.pm
argv = -severity 3
```

Problem is that in the ignore line, the second part is ignored. It only works if the two arguments are on two separate ignore lines. I found this by travis reporting errors on our tests which have a fairly huge configuration file at https://github.com/OTRS/otrscodepolicy/blob/master/Kernel/TidyAll/tidyallrc where we often specify more than one entry per line (as suggested by the TidyAll docs - therefore I assume this is a regression).

Could you please check this issue?

Thanks and best regards, 
Martin

**Comment by mgruner** [comment]
Correction: the ignore line with more than one entry is completely ignored. :smile:

**Comment by autarch** [comment]
Thanks, this was never tested in the distro. I fixed this and added some tests. The new release should be out shortly.

**Comment by mgruner** [comment]
Excellent, thank you so much @autarch!
