### ISSUE TITLE
0.52 changes file permissions

### ISSUE THREAD

**Issue by mgruner** [houseabsolute/perl-code-tidyall#68]
When making a change in a script file (like .pl) with 755 permissions, Code::TidyAll will always change file permissions to 644. This was not the case with 0.49.

BTW, is it possible to voluntarily modify file permissions in a TidyAll plugin?

@ManuelHecht: FYI

**Comment by adamherzog** [comment]
I just ran into this myself. Git bisect helped me track it to something in commit 2cd8ffb3b128127c7fa92c5e2a9c5c4ecd3fc98a.

I'll try and put together a failing test case and then track down the bug.

**Comment by autarch** [comment]
Fixed in 0.53
