### ISSUE TITLE
Feature request: add global ignores

### ISSUE THREAD

**Issue by mgruner** [houseabsolute/perl-code-tidyall#70]
It would be tremendously helpful to be able to specify global ignores, files and directories that are known to never need any validation. Right now this can only be specified per-plugin, as far as I can tell. Thanks for considering!

**Comment by autarch** [comment]
I agree, this would be very useful.

I think it would make sense to simple have these are section-less INI style directives, like:

```
ignore = ...
ignore = ...
some_future_thing = 42

[PerlTidy]
select = **/*.{pl,pm,t,psgi}
...
```

The config parser should return these as `$config->{_}{ignore}`.

A PR for this would be very welcome.

**Comment by mgruner** [comment]
Please see #73.

**Comment by autarch** [comment]
Added in 0.56
