### ISSUE TITLE
Tests fail on ms windows / Strawberry Perl

### ISSUE THREAD

**Issue by shlomif** [houseabsolute/perl-code-tidyall#90]
See https://ci.appveyor.com/project/shlomif/latemp/builds/21635207 . I tried:

```
cpanm --verbose Test::Code::TidyAll
```

and got tests failure. There also seems to be CPAN testers failures.

**Comment by autarch** [comment]
Oops, somehow the fact that this distro was failing its _own_ AppVeyor testing escaped me (https://ci.appveyor.com/project/autarch/perl-code-tidyall/builds/21154767)

**Comment by shlomif** [comment]
@autarch : thanks for looking into it.

**Comment by shlomif** [comment]
@autarch : hi! Can I help somehow?

**Comment by autarch** [comment]
@shlomif A PR would be welcome. It looks like the failure is from the new GenericValidator and GenericTransformer plugin tests. I'm guessing that somehow the command being tested isn't being executed properly on Windows.

**Comment by shlomif** [comment]
On Fri, 18 Jan 2019 22:47:29 +0000 (UTC)
Dave Rolsky <notifications@github.com> wrote:

> @shlomif A PR would be welcome. It looks like the failure is from the new
> GenericValidator and GenericTransformer plugin tests. I'm guessing that
> somehow the command being tested isn't being executed properly on Windows.
> 

thanks! I'll try.


-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
http://www.shlomifish.org/humour/bits/Can-I-SCO-Now/ - “Can I SCO Now?”

There was one Napoleon, one George Washington, and one me!
    — Big Boy Caprice in
       http://en.wikiquote.org/wiki/Dick_Tracy_%281990_film%29

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by autarch** [comment]
Fixed in 0.73.

**Comment by shlomif** [comment]
On Sat, 26 Jan 2019 09:30:50 -0800
Dave Rolsky <notifications@github.com> wrote:

> Fixed in 0.73.
> 

Thanks!

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
https://github.com/sindresorhus/awesome - curated list of lists

Thank you! I was wondering why I hated Eclipse so much, and you have put your
finger on it. It’s exactly like a 21st century Emacs.
    — Shachar Shemesh on the Haifa Linux Club mailing list.

Please reply to list if it's a mailing list post - http://shlom.in/reply .
