### ISSUE TITLE
Slight documentation issue

### ISSUE THREAD

**Issue by davehodg** [houseabsolute/perl-code-tidyall#96]
Nick Tonkin is credited twice in the man page, once with a noreply address:

    *   Nick Tonkin <1nickt@users.noreply.github.com>

    *   Nick Tonkin <ntonkin@bur-ntonkin-m1.corp.endurance.com>

Trivial, right?

**Comment by autarch** [comment]
Yes, this just needs a `.mailmap` line to fix.
