### ISSUE TITLE
Not respecting args or something else

### ISSUE THREAD

**Issue by renatocron** [houseabsolute/perl-code-tidyall#98]
Hello,

I'm trying to tidy this file: https://gist.github.com/renatocron/b2303649bd4d5f6a6440c3ccfe563806 
with this options:
```-pbp      # Start with Perl Best Practices
-w        # Show all warnings
-iob      # Ignore old breakpoints
-l=120    # Break lines
-mbl=2    # No more than 2 blank lines
-i=4      # Indentation is 4 columns
-ci=2     # Continuation indentation is 2 columns
-vt=0     # Less vertical tightness
-pt=2     # High parenthesis tightness
-bt=2     # High brace tightness
-sbt=2    # High square bracket tightness
-isbc     # Don't indent comments without leading space
-nst      # Don't output to STDOUT
-boc      # Don't collapse all itens into one
```

This is how tidyall.ini looks like:

```
[PerlTidy]
argv = -pbp -w -iob -l=120 -mbl=2 -i=4 -ci=2 -vt=0 -pt=2 -bt=2 -sbt=2 -isbc -nst -boc
select = **/*.{pl,pm,t}

```

But when running with this options, I get this result:
`tidyall --conf-name tidyall.ini lib/TouchBase/Schema/ResultSet/Voucher.pm`

https://gist.github.com/renatocron/da67f3bfa37eba8fce9b2f30ecf962d9

At sub build_list everything is collapsed into one hash (-boc is ignored)

If I restore the original, and run with `perltidy -b -pbp -w -iob -l=120 -mbl=2 -i=4 -ci=2 -vt=0 -pt=2 -bt=2 -sbt=2 -isbc -nst -boc lib/TouchBase/Schema/ResultSet/Voucher.pm` the file kept the same (because it's already formatted as expected by the options, and second / third runs is stable, `-b` is just for in-place edit)

I'm also running on sublime using the same options, it get as expected.

How can I debug this? there's a trace env to see what is being executed? 

For now I'm using this hack: 
```
find . -name "*.pl" -exec perltidy -b -bext='/' -pbp -w -iob -l=120 -mbl=2 -i=4 -ci=2 -vt=0 -pt=2 -bt=2 -sbt=2 -isbc -nst -boc {} \;
find . -name "*.pm" -exec perltidy -b -bext='/' -pbp -w -iob -l=120 -mbl=2 -i=4 -ci=2 -vt=0 -pt=2 -bt=2 -sbt=2 -isbc -nst -boc {} \;
```

but it's quite slow :laughing:

**Comment by autarch** [comment]
Hi Renato,

Thanks for the bug report.

I recreated your config and when I run `tidyall -a` I get this:

```
tidyall -a
[checked] Foo.pm
Conflicting parameters: -iob and -boc; -boc will be ignored
```

So I think the problem is the set of options you're passing to perltidy, not tidyall.
